### ISSUE TITLE
Redirection link on documentation return a wrong url

### ISSUE THREAD

**Issue by zazapeta** [RedisDesktop/redisdesktop.com#17]
<li><a rel="nofollow" href="http://docs.redisdesktop.com/">Documentation [http://docs.redisdesktop.com/]</a></li>

should be 

<li><a rel="nofollow" href="http://docs.redisdesktop.com/en/latest/">Documentation [http://docs.redisdesktop.com/en/latest/]</a></li>

Isn't it ?

**Comment by uglide** [comment]
@zazapeta you are right, thanks!
